### PR TITLE
merging changes from 1sp-in to the blog branch

### PR DESCRIPTION
**Pull request by 1sp**

### CODE REVIEW

**Comment by 1sp** [comment]
@KathJohnson  @jboz62 shall I merge this pull request ?

**Comment by jboz62** [comment]
I would say yes, but if you feel more comfortable waiting to hear from Katherine, please do. I have reviewed the changes and everything seems to be working well. There may be small changes down the road, but this works great for what we need to get done. Thank you.

**Comment by 1sp** [comment]
Just did the merge. @jboz62 thanks for all the help. I hope the functionality works well. In case of any issues, I am around.

**Comment by jboz62** [comment]
Thanks, Sudhir!

**Comment by jboz62** [comment]
@1sp I ran a deploy on lightthemetest and hit an error on page load:

screen shot 2016-05-06 at 4 26 33 pm

**Comment by 1sp** [comment]
This is wierd. This implies that portfolio position couldn't be set in the
menu array. I am debugging this right now

On Sat, May 7, 2016 at 1:57 AM, jboz62 <notifications@github.com> wrote:

> @1sp <https://github.com/1sp> I ran a deploy on lightthemetest and hit an
> error on page load:
>
> [image: screen shot 2016-05-06 at 4 26 33 pm]
> <https://cloud.githubusercontent.com/assets/11739120/15085284/64c26fc6-13a7-11e6-8bbf-dc1e43948fd2.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/meetinghouse/cms/pull/249#issuecomment-217549839>
>



-- 
Sudhir Porwal

**Comment by 1sp** [comment]
Exactly what I suspected, the database had no pages with new menu type
hence menu was coming empty which made code raise exception.

Let me make a migration which will automatically convert all 'top' or
'left_side' menu items into 'top,left_side' hence preventing this scenario
to happen.

On Sat, May 7, 2016 at 2:03 AM, Sudhir <skporwal@gmail.com> wrote:

> This is wierd. This implies that portfolio position couldn't be set in the
> menu array. I am debugging this right now
>
> On Sat, May 7, 2016 at 1:57 AM, jboz62 <notifications@github.com> wrote:
>
>> @1sp <https://github.com/1sp> I ran a deploy on lightthemetest and hit
>> an error on page load:
>>
>> [image: screen shot 2016-05-06 at 4 26 33 pm]
>> <https://cloud.githubusercontent.com/assets/11739120/15085284/64c26fc6-13a7-11e6-8bbf-dc1e43948fd2.png>
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/meetinghouse/cms/pull/249#issuecomment-217549839>
>>
>
>
>
> --
> Sudhir Porwal
>
>


-- 
Sudhir Porwal

**Comment by jboz62** [comment]
That makes sense, we need to deploy to older sites and all have old pages. 

--
John Bozaan
Bozaan Design
413-437-0097

**Comment by 1sp** [comment]
John, I just merged a migration into 'blog'. Can you please re-deploy on
lightthemetest once more to see if everything works well ?

On Sat, May 7, 2016 at 2:31 AM, jboz62 <notifications@github.com> wrote:

> That makes sense, we need to deploy to older sites and all have old pages.
>
> --
> John Bozaan
> Bozaan Design
> 413-437-0097
>
> > On May 6, 2016, at 4:48 PM, Sudhir <notifications@github.com> wrote:
> >
> > Exactly what I suspected, the database had no pages with new menu type
> > hence menu was coming empty which made code raise exception.
> >
> > Let me make a migration which will automatically convert all 'top' or
> > 'left_side' menu items into 'top,left_side' hence preventing this
> scenario
> > to happen.
> >
> > On Sat, May 7, 2016 at 2:03 AM, Sudhir <skporwal@gmail.com> wrote:
> >
> > > This is wierd. This implies that portfolio position couldn't be set in
> the
> > > menu array. I am debugging this right now
> > >
> > > On Sat, May 7, 2016 at 1:57 AM, jboz62 <notifications@github.com>
> wrote:
> > >
> > >> @1sp <https://github.com/1sp> I ran a deploy on lightthemetest and
> hit
> > >> an error on page load:
> > >>
> > >> [image: screen shot 2016-05-06 at 4 26 33 pm]
> > >> <
> https://cloud.githubusercontent.com/assets/11739120/15085284/64c26fc6-13a7-11e6-8bbf-dc1e43948fd2.png
> >
> > >>
> > >> —
> > >> You are receiving this because you were mentioned.
> > >> Reply to this email directly or view it on GitHub
> > >> <https://github.com/meetinghouse/cms/pull/249#issuecomment-217549839>
> > >>
> > >
> > >
> > >
> > > --
> > > Sudhir Porwal
> > >
> > >
> >
> >
> > --
> > Sudhir Porwal
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/meetinghouse/cms/pull/249#issuecomment-217557428>
>



-- 
Sudhir Porwal

**Comment by jboz62** [comment]
I redeployed to lightthemetest, you can see it live now.

**Comment by 1sp** [comment]
Sorry, can you please redeploy again? I have updated the database on lightthemetest via sftp

**Comment by jboz62** [comment]
Thank you, Sudhir. Seems there is still something not quite right, after I tried to edit the home page name to “home”, I got the same error as before. Now I can’t get back into the site.

**Comment by 1sp** [comment]
please join me at https://join.me/498-317-162

**Comment by jboz62** [comment]
Done. Shouldn’t the index be defaulting to the 0 or 1? I can set it, there, I think, but seems like that should just be the default. What do you think?

**Comment by 1sp** [comment]
lightthemetest seems to be loading up fine now

**Comment by 1sp** [comment]
Which index you are talking about ?

**Comment by 1sp** [comment]
are you there with me on the join.me session ?

**Comment by jboz62** [comment]
Trying to do the Join.me <http://join.me/>, Sudhir, having trouble with my computer, one moment…

**Comment by jboz62** [comment]
The “home” menu item I just changed. Was at the bottom of the list, I moved it to the top and changed the title.

**Comment by jboz62** [comment]
No, the URL was no longer valid. Can you start a new session and send me the link again? Thank you

**Comment by jboz62** [comment]
The URL on the home page is usually /index, not sure if that matters.

screen shot 2016-05-06 at 6 09 58 pm

**Comment by jboz62** [comment]
Is it possible to make "home" default to the 0 or 1 position, whichever is the top? I'm not sure how this system work yet, but is there an "index" page on this, or are they all just the same and one happens to have the slug as /index?

**Comment by jboz62** [comment]
Sudhir, everything seems to be working now, thank you for working at such a late hour for you. Get some rest, and have a good weekend.

**Pull request merged**
