### PR TITLE
Fix for broken active class logic on menu items

### PR DESCRIPTION
**Pull request by 1sp**

### CODE REVIEW

**Comment by jboz62** [comment]
@1sp Looks great! Please merge with "blog". Thank you for the work on this.

**Comment by 1sp** [comment]
John , I have just created a pull request intended for blog branch. Shall I
do the merge or Katherine would do it ?

On Sat, May 7, 2016 at 12:41 AM, jboz62 <notifications@github.com> wrote:

> @1sp <https://github.com/1sp> Looks great! Please merge with "blog".
> Thank you for the work on this.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/meetinghouse/cms/pull/248#issuecomment-217533035>
>



-- 
Sudhir Porwal

**Comment by 1sp** [comment]
Oops, did I merged it already ?

**Comment by 1sp** [comment]
Please ignore the last comment. I forgot this is an already merged old pull request.

**Pull request merged**
