### PR TITLE
New menu management sub-system

### PR DESCRIPTION
**Pull request by 1sp**
All the changes till now(excluding /menus). The system is tested using an admin login.

### CODE REVIEW

**Comment by KathJohnson** [comment]
Am I safe to merge this pull request? I ask because this is the real-live code branch, so any deployment that occur after this will include it.

**Comment by jboz62** [comment]
He didn’t add the pull request to a new branch? No, I wouldn’t add this to “blog”, if it’s not in a new branch I will ask him to fix that.

**Comment by jboz62** [comment]
@1sp Hi Sudhir, it looks like you committed your changes to the "blog" branch. That's the master branch, can you create a new branch from blog and commit your changes there, then redo the pull request. Thank you.

**Comment by 1sp** [comment]
oops, my bad. I totally forgot that blog is the live branch. Making a new pull request accordingly

**Comment by jboz62** [comment]
@1sp Sudhir, can this pull request be closed without damaging or deleting "blog"? We will merge the other pull request you did, we don't need this one so it can be removed.

**Comment by 1sp** [comment]
Done!

**Pull request closed without merging**
