### PR TITLE
Dark theme changes

### PR DESCRIPTION
**Pull request by jboz62**
Changes for dark theme to split layout and functionality between dark and light themes.

### CODE REVIEW

**Comment by jboz62** [comment]
@KathJohnson Hi Katherine, here are the changes for the dark theme that will also add the functionality for S+H. Please merge at your when you can. Thanks!

**Comment by jboz62** [comment]
Great, thanks! Can you deploy that to S+H? After that we should be pretty close to launch, just need to make those tweaks to issue #219 <https://github.com/meetinghouse/cms/issues/219> and whatever changes you need to make.


John Bozaan
Bozaan Design
413-437-0097
www.bozaandesign.com

**Comment by meetinghouse** [comment]
Deploy is done, all looks good. The client wants to launch today, I just
found. They have specifically said that the changes to the project page
format aren't crucial to be done before launch.

Do you mind holding off on them, in that case? Maybe give the site a week
or so of stability after launch, and then changes can begin again. On the
other hand, if it is to be done momentarily, I will wait a bit. You can
direct me on which is better for you.


Side question: Are the changes going to happen in their custom css file or
in the Git code?

Sincerely,
Katherine Johnson, Research Director
Corbett Research Group
http://www.restorationtrades.com
"Web Marketing that Works"

Publishers of:

The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

The Building Arts Notebook, "Journal of the Guild of Building Artisans"
http://buildingartisansguild.com/

Email:  katherine@restorationtrades.com
Phone: 413-586-4748

**Comment by jboz62** [comment]
Feel free to launch if it’s not that important to them, I can get the changes done soon. That will only be in the custom css file, so no git needed.


John Bozaan
Bozaan Design
413-437-0097
www.bozaandesign.com

**Comment by meetinghouse** [comment]
Great. Let's leave it for a week or so, then. I'll put calendar asking you
about it next week and if you want to move on to another issue, that would
probably be good.

Sincerely,
Katherine Johnson, Research Director
Corbett Research Group
http://www.restorationtrades.com
"Web Marketing that Works"

Publishers of:

The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

The Building Arts Notebook, "Journal of the Guild of Building Artisans"
http://buildingartisansguild.com/

Email:  katherine@restorationtrades.com
Phone: 413-586-4748

**Pull request merged**
